repositories:
  remote:
   - https://stocksoftware.jfrog.io/stocksoftware/maven2
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/staging

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.14

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.106

  testng: org.testng:testng:jar:6.11

  jetbrains_annotations: org.realityforge.org.jetbrains.annotations:org.jetbrains.annotations:jar:1.3.0

  javacsv: net.sourceforge.javacsv:javacsv:jar:2.1
