repositories:
  remote:
   - http://repo1.maven.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/public
   - https://stocksoftware.jfrog.io/stocksoftware/oss
   - https://stocksoftware.jfrog.io/stocksoftware/thirdparty-local

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.13

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.0

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.95

  testng: org.testng:testng:jar:6.11

  jetbrains_annotations: org.realityforge.org.jetbrains.annotations:org.jetbrains.annotations:jar:1.0.0

  javacsv: net.sourceforge.javacsv:javacsv:jar:2.1
